import type { RegionSpec } from './types.ts'

const CONVERSATION = ['canvas', 'read', 'history'] as const
const EVERYWHERE = ['desk', 'canvas', 'read', 'history', 'jump', 'comment'] as const

/**
 * A region names a place on the screen, never its contents, so there is no region
 * per card or per turn. An empty `states` list means the driver cannot reach the
 * state the region lives in; the report names those rather than hiding them.
 *
 * `quotes` marks the regions that render a conversation rather than the app's own
 * words. The fallback-string scan bites on chrome only: inside quoted content a
 * word like "undefined" is something someone wrote, not a binding that broke.
 */
export const REGIONS: RegionSpec[] = [
  {
    id: 'desk',
    label: 'desk',
    design: 'The whole desk: every conversation as a card.',
    selectors: ['[data-region="desk"]'],
    demand: 'required',
    states: ['desk'],
    quotes: true,
  },
  {
    id: 'desk-head',
    label: 'desk head',
    design: 'Top left: the sidecar mark and a count of conversations and what waits.',
    selectors: ['[data-region="desk-head"]'],
    demand: 'required',
    states: ['desk'],
  },
  {
    id: 'desk-card',
    label: 'desk card',
    design: 'One conversation: live dot, waiting badge, artifact chips, mode and style, board count.',
    selectors: ['[data-region="desk-card"]'],
    demand: 'empty-ok',
    states: ['desk'],
    namesNotIds: true,
    quotes: true,
  },

  {
    id: 'conversation-head',
    label: 'conversation head',
    design: 'Top left: back to desk, the conversation title, its working directory.',
    selectors: ['[data-region="conversation-head"]'],
    demand: 'required',
    states: [...CONVERSATION, 'comment'],
    namesNotIds: true,
  },
  {
    id: 'conversation-title',
    label: 'conversation title',
    design: 'The conversation by name, never its key, beside the working directory.',
    selectors: ['[data-region="conversation-title"]'],
    demand: 'required',
    states: [...CONVERSATION, 'comment'],
    namesNotIds: true,
    quotes: true,
  },
  {
    id: 'conversation-stage',
    label: 'conversation stage',
    design: 'The face currently showing, carrying data-face.',
    selectors: ['[data-region="conversation-stage"]'],
    demand: 'required',
    states: [...CONVERSATION, 'comment'],
    quotes: true,
  },
  {
    id: 'top-right',
    label: 'top right',
    design: 'The chrome cluster: view switcher and comment arm at a conversation, theme everywhere.',
    selectors: ['[data-region="top-right"]'],
    demand: 'required',
    states: [...EVERYWHERE],
  },
  {
    // Absent by design below two built faces, so a missing one warns rather than fails.
    id: 'view-switcher',
    label: 'view switcher',
    design: 'Canvas, Read and History — only the faces whose domain is actually built.',
    selectors: ['[data-region="view-switcher"]'],
    demand: 'empty-ok',
    states: [...CONVERSATION],
  },
  {
    id: 'comment-arm',
    label: 'comment button',
    design: 'Arms the page so anything on it can be commented on.',
    selectors: ['[data-region="comment-arm"]'],
    demand: 'required',
    states: [...CONVERSATION],
  },
  {
    id: 'theme-toggle',
    label: 'theme toggle',
    design: 'Far right of the top row, on every screen.',
    selectors: ['[data-region="theme-toggle"]'],
    demand: 'required',
    states: [...EVERYWHERE],
  },
  {
    id: 'canvas-zoom',
    label: 'zoom readout',
    design: 'The canvas zoom as a percentage, appearing once a mounted canvas registers it.',
    selectors: ['[data-region="canvas-zoom"]'],
    demand: 'empty-ok',
    states: ['canvas'],
  },

  {
    id: 'canvas',
    label: 'canvas',
    design: 'The pan and zoom plane: artifacts where they were made, task frames, links, notes.',
    selectors: ['[data-region="canvas"]'],
    demand: 'required',
    states: ['canvas'],
    quotes: true,
  },
  {
    id: 'read-view',
    label: 'read view',
    design: 'The artifact with its version tabs, comment pills and threads.',
    selectors: ['[data-region="read-view"]'],
    demand: 'required',
    states: ['read'],
    quotes: true,
  },
  {
    id: 'version-tabs',
    label: 'version tabs',
    design: 'One tab per version, with a Latest button.',
    selectors: ['[data-region="version-tabs"]'],
    demand: 'empty-ok',
    states: ['read'],
  },
  {
    id: 'version-badge',
    label: 'version badge',
    design: 'The version showing and the turn that wrote it. Live since the store shipped.',
    selectors: ['[data-region="version-badge"]'],
    demand: 'empty-ok',
    states: ['read'],
  },
  {
    id: 'artifact-page',
    label: 'artifact page',
    design: 'The artifact itself, rendered in its own frame.',
    selectors: ['[data-region="artifact-page"]'],
    demand: 'required',
    states: ['read'],
    quotes: true,
    frame: true,
  },
  {
    id: 'gutter-markers',
    label: 'gutter markers',
    design: 'A numbered marker in the left margin beside the block it anchors to.',
    selectors: ['[data-region="gutter-markers"]'],
    demand: 'empty-ok',
    states: ['read'],
    quotes: true,
  },
  {
    id: 'history',
    label: 'history',
    design: 'Turns down the left, per-file diffs on the right.',
    selectors: ['[data-region="history"]'],
    demand: 'required',
    states: ['history'],
  },
  {
    id: 'history-turns',
    label: 'history turns',
    design: 'Every turn, attributed, with the new-since divider.',
    selectors: ['[data-region="history-turns"]'],
    demand: 'required',
    states: ['history'],
    quotes: true,
  },
  {
    id: 'history-changes',
    label: 'history changes',
    design: 'What the selected turn changed, per file, with compare and restore.',
    selectors: ['[data-region="history-changes"]'],
    demand: 'required',
    states: ['history'],
    quotes: true,
  },

  {
    id: 'composer-dock',
    label: 'composer',
    design: 'Bottom left: the prompt, the tray, the transcript, the mode and style pickers.',
    selectors: ['[data-region="composer-dock"]'],
    demand: 'required',
    states: [...CONVERSATION, 'comment'],
    quotes: true,
  },
  {
    id: 'composer-tray',
    label: 'composer tray',
    design: 'The comments waiting to ride the next turn. Legitimately empty until one is left.',
    selectors: ['[data-region="composer-tray"]'],
    demand: 'empty-ok',
    states: [...CONVERSATION],
    quotes: true,
  },
  {
    id: 'composer-transcript',
    label: 'composer transcript',
    design: 'The turns so far, collapsible to one line and minimizable away.',
    selectors: ['[data-region="composer-transcript"]'],
    demand: 'empty-ok',
    states: [...CONVERSATION],
    quotes: true,
  },
  {
    id: 'mode-picker',
    label: 'mode picker',
    design: 'How the next turn runs, with the pipeline diagram on hover.',
    selectors: ['[data-region="mode-picker"]'],
    demand: 'required',
    states: [...CONVERSATION],
  },
  {
    id: 'style-picker',
    label: 'style picker',
    design: 'How the next turn sounds.',
    selectors: ['[data-region="style-picker"]'],
    demand: 'required',
    states: [...CONVERSATION],
  },
  {
    id: 'board-island',
    label: 'board island',
    design: 'Bottom right: the shared board, open or minimized to a pill.',
    selectors: ['[data-region="board-island"]'],
    demand: 'required',
    states: [...CONVERSATION],
    quotes: true,
  },

  {
    id: 'jump-palette',
    label: 'jump palette',
    design: 'Command-K: filter conversations by name, arrows to move, enter to open.',
    selectors: ['[data-region="jump-palette"]'],
    demand: 'required',
    states: ['jump'],
    namesNotIds: true,
    quotes: true,
  },
  {
    id: 'comment-mode',
    label: 'comment overlay',
    design: 'The armed layer over the whole page.',
    selectors: ['[data-region="comment-mode"]'],
    demand: 'required',
    states: ['comment'],
  },
  {
    id: 'comment-banner',
    label: 'comment banner',
    design: '"Pick anything to comment on", in the transient lane.',
    selectors: ['[data-region="comment-banner"]'],
    demand: 'required',
    states: ['comment'],
  },
  {
    id: 'comment-popover',
    label: 'comment popover',
    design: 'What Claude will be told about the picked element, above the box you type in.',
    selectors: ['[data-region="comment-popover"]'],
    demand: 'required',
    states: ['comment'],
    quotes: true,
  },

  // Below here the driver cannot reach the state, and the report says so rather
  // than letting a spec describe something nothing checks.
  {
    id: 'canvas-empty',
    label: 'canvas empty',
    design: 'Shown only when a conversation has made no artifact and holds no note.',
    selectors: ['[data-region="canvas-empty"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'canvas-menu',
    label: 'canvas menu',
    design: 'The right-click menu, teleported to body so it escapes the plane transform.',
    selectors: ['[data-region="canvas-menu"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'read-thread',
    label: 'read thread',
    design: 'A comment thread on a block, teleported out of the pane.',
    selectors: ['[data-region="read-thread"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'read-compose',
    label: 'read compose',
    design: 'The box for a new comment on selected text.',
    selectors: ['[data-region="read-compose"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'select-to-comment',
    label: 'select to comment',
    design: 'The floating Comment button over a text selection inside the artifact frame.',
    selectors: ['[data-region="select-to-comment"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'read-gap',
    label: 'read gap',
    design: 'What is said when the store cannot return the version being asked for.',
    selectors: ['[data-region="read-gap"]'],
    demand: 'empty-ok',
    states: [],
  },
  {
    id: 'toaster',
    label: 'toaster',
    design: 'The transient lane, top center, empty at rest.',
    selectors: ['[data-region="toaster"]'],
    demand: 'empty-ok',
    states: [],
  },
]

export const PLACEHOLDER_PATTERNS: string[] = [
  'No\\s+[\\w\\s-]{1,40}?\\s+mounted yet',
  'coming soon',
  'not implemented',
  'nothing here yet',
  'TODO',
  'FIXME',
  'lorem ipsum',
  'placeholder',
  '\\[object Object\\]',
  '\\bundefined\\b',
  '\\bNaN\\b',
]
