import type { RegionSpec } from './types.ts'

export const REGIONS: RegionSpec[] = [
  {
    id: 'session-tabs',
    label: 'session tabs',
    design: 'One tab per live conversation. Real names, never a session id.',
    // no generic fallback: a loose selector matched the panel's tablist and reported a false OK
    selectors: ['[data-region="session-tabs"]', '.folio-rail'],
    demand: 'required',
    states: ['open'],
    namesNotIds: true,
  },
  {
    id: 'artifact-switcher',
    label: 'artifact switcher',
    design: "A segmented switcher of that session's artifacts, one pill each.",
    selectors: ['[data-region="artifact-switcher"]', '.folio-shelf'],
    demand: 'required',
    states: ['open'],
  },
  {
    id: 'version-badge',
    label: 'version badge',
    design: 'Right of the switcher, in mono uppercase: "V3 · 4 MIN AGO".',
    selectors: ['[data-region="version-badge"]'],
    demand: 'inert',
    states: ['open'],
  },
  {
    id: 'artifact-page',
    label: 'artifact page',
    design: 'Below it, the artifact itself, rendered.',
    selectors: ['[data-region="artifact-page"]', '.folio-page--left'],
    demand: 'required',
    states: ['open', 'closed'],
    frame: true,
  },
  {
    id: 'panel-tabs',
    label: 'panel tabs',
    design: 'Notes 2 (active, with a count), Pipeline, History v3. Far right, a live state dot.',
    selectors: ['[data-region="panel-tabs"]'],
    demand: 'required',
    states: ['open'],
  },
  {
    id: 'question-card',
    label: 'question card',
    design: 'Eyebrow "CLAUDE ASKS · BLOCKS SHAPE", the question in bold, radio options.',
    selectors: ['[data-region="question-card"]'],
    demand: 'inert',
    states: ['open'],
  },
  {
    id: 'notes',
    label: 'notes',
    design: 'Notes grouped under the section they anchor to.',
    selectors: ['[data-region="notes"]', '.folio-page--right'],
    demand: 'empty-ok',
    states: ['open'],
  },
  {
    id: 'panel-footer',
    label: 'panel footer',
    design: 'The two slot chips, a ground-rule count "ground · 3/7", and the prompt input.',
    selectors: ['[data-region="panel-footer"]'],
    demand: 'required',
    states: ['open'],
  },
  {
    id: 'prompt-input',
    label: 'prompt input',
    design: 'Phase 4. Disabled with a one-line reason, not left looking broken.',
    selectors: ['[data-region="prompt-input"]'],
    demand: 'inert',
    states: ['open'],
  },
  {
    id: 'session-capsule',
    label: 'session capsule',
    design: 'Floating top left: "docs-site › Search index explainer 2/3".',
    selectors: ['[data-region="session-capsule"]'],
    demand: 'required',
    states: ['closed'],
    namesNotIds: true,
  },
  {
    id: 'awaiting-island',
    label: 'awaiting-you island',
    design: 'Floating top right: "2 waiting for you", then "1 question · 1 gate".',
    selectors: ['[data-region="awaiting-island"]'],
    demand: 'required',
    states: ['closed'],
  },
  {
    id: 'gutter-markers',
    label: 'gutter markers',
    design: 'A small numbered marker in the left margin beside the section it belongs to.',
    selectors: ['[data-region="gutter-markers"]'],
    demand: 'empty-ok',
    states: ['closed'],
  },
  {
    id: 'pipeline-island',
    label: 'pipeline island',
    design: 'Slot chips, the steps in mono uppercase, the live state, a circular send button.',
    selectors: ['[data-region="pipeline-island"]', '.pipeline-island'],
    demand: 'required',
    states: ['open', 'closed'],
  },
]

export const PLACEHOLDER_PATTERNS: string[] = [
  'No\\s+[\\w\\s-]{1,40}?\\s+mounted yet',
  'coming soon',
  'not implemented',
  'nothing here yet',
  'TODO',
  'FIXME',
  'lorem ipsum',
  'placeholder',
  '\\[object Object\\]',
  '\\bundefined\\b',
  '\\bNaN\\b',
]

export const PANEL_TOGGLE_SELECTORS: string[] = [
  '[data-region-toggle="panel"]',
  '[data-panel-toggle]',
]
