import assert from "node:assert/strict"
import { test } from "node:test"
import { argOf, noteOf, readOut, withoutReminders } from "./speaker.ts"

test("a task notification is a system note, not something Marco typed", () => {
  const raw = "<task-notification>\n<task-id>bosn7ubs9</task-id>\n<status>completed</status>\n</task-notification>"
  assert.deepEqual(noteOf(raw), { label: "Task(bosn7ubs9)" })
})

test("a typed message is nobody's note, however long", () => {
  assert.equal(noteOf("build it"), undefined)
  assert.equal(noteOf("here is a sample of message: hey can you help me answering the comment?"), undefined)
})

test("a reminder wrapping real words is context, but a bare one is the whole message", () => {
  const wrapped = "fix the failing test<system-reminder>be careful</system-reminder>"
  assert.equal(noteOf(wrapped), undefined)
  assert.equal(withoutReminders(wrapped), "fix the failing test")
  assert.deepEqual(noteOf("<system-reminder>the board went up late</system-reminder>"), { label: "System reminder" })
})

test("a bare slash command is a note, but a path starting with one is not", () => {
  assert.deepEqual(noteOf("/compact"), { label: "Command(compact)" })
  assert.deepEqual(noteOf("/style edu"), { label: "Command(style)" })
  assert.deepEqual(noteOf("/mode:autopilot"), { label: "Command(mode:autopilot)" })
  assert.equal(noteOf("/Users/madong/Notes"), undefined)
})

test("a caveat wrapper is a note like the other harness tags", () => {
  assert.deepEqual(noteOf("<local-command-caveat>Caveat: The messages below were generated by the user…</local-command-caveat>"), {
    label: "Session caveat",
  })
})

test("a harness wrapper sharing an entry with real prose keeps the prose after its note", () => {
  const raw = "<local-command-caveat>Caveat: ignore these</local-command-caveat>\nactually please fix the bug"
  assert.deepEqual(readOut(raw), [
    { kind: "note", label: "Session caveat" },
    { kind: "said", text: "actually please fix the bug" },
  ])
})

test("an action carries the one argument worth reading", () => {
  assert.equal(argOf("Read", { file_path: "/Users/madong/Notes/projects/Cela/Mode/server/utils/sessions/relay.ts" }), "sessions/relay.ts")
  assert.equal(argOf("Grep", { pattern: "mode-relay", output_mode: "content" }), "mode-relay")
  assert.equal(argOf("Skill", { skill: "create-artifact" }), "create-artifact")
  assert.equal(argOf("TaskUpdate", { taskId: "42", status: "completed" }), "42")
})

// Bash prefers the description because the command is often long and quoted.
test("Bash reads as what it was for, not the command line", () => {
  assert.equal(argOf("Bash", { command: "pnpm test 2>&1 | grep -E 'pass|fail'", description: "Run the test suite" }), "Run the test suite")
  assert.equal(argOf("Bash", { command: "git status --short" }), "git status --short")
})

test("a tool with nothing worth showing renders bare", () => {
  assert.equal(argOf("TaskList", {}), undefined)
  assert.equal(argOf("Read", undefined), undefined)
})

// The marker sits between a withdrawn ask and the next one, so anchoring it to the start missed it.
test("an interruption splits the message and keeps the order", () => {
  const raw = "Mark task #11 as done.\n[Request interrupted by user]\nhandle system signals like interrupted"
  assert.deepEqual(readOut(raw), [
    { kind: "said", text: "Mark task #11 as done." },
    { kind: "note", label: "Interrupted" },
    { kind: "said", text: "handle system signals like interrupted" },
  ])
})

test("an interruption with nothing after it is just the withdrawal", () => {
  assert.deepEqual(readOut("do the thing\n[Request interrupted by user for tool use]"), [
    { kind: "said", text: "do the thing" },
    { kind: "note", label: "Interrupted" },
  ])
})

test("an ordinary message is one piece, and a tagged one is one note", () => {
  assert.deepEqual(readOut("build it"), [{ kind: "said", text: "build it" }])
  assert.deepEqual(readOut("<task-notification>\n<task-id>abc123</task-id>\n</task-notification>"), [
    { kind: "note", label: "Task(abc123)" },
  ])
})
