import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

type Report = { viewBox: string; tracks: { fill: string; frames: string[] }[] };

const report: Report = JSON.parse(readFileSync(join(HERE, "mascot-frames.json"), "utf8"));

function box(d: string): [number, number, number, number] {
  const n = (d.match(/-?\d*\.?\d+/g) ?? []).map(Number);
  const xs = n.filter((_, i) => i % 2 === 0);
  const ys = n.filter((_, i) => i % 2 === 1);
  return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)];
}

// One box across every drawing track, so a frame never jumps because its own bounds are tighter.
const drawn = report.tracks.filter((t) => t.frames.length > 1);
let [minX, minY, maxX, maxY] = [Infinity, Infinity, -Infinity, -Infinity];
for (const track of drawn) {
  for (const frame of track.frames) {
    const [a, b, c, e] = box(frame);
    minX = Math.min(minX, a); minY = Math.min(minY, b);
    maxX = Math.max(maxX, c); maxY = Math.max(maxY, e);
  }
}
const VB = `${minX} ${minY} ${maxX - minX} ${maxY - minY}`;

const svg = (fill: string, d: string, size: number) =>
  `<svg viewBox="${VB}" width="${size}" height="${size}" style="display:block"><path fill="${fill}" d="${d}"></path></svg>`;

const sheets = report.tracks
  .map((track, ti) => {
    const cells = track.frames
      .map((d, fi) => `<div class="cell">${svg(track.fill, d, 150)}<span>t${ti} f${String(fi).padStart(2, "0")}</span></div>`)
      .join("");
    return `<h2>track ${ti} &mdash; ${track.fill} &mdash; ${track.frames.length} frames</h2><div class="sheet">${cells}</div>`;
  })
  .join("");

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mascot frames</title>
<!-- Generated by tools/mascot-bench.ts from tools/mascot-frames.json. Do not hand-edit. -->
<style>
:root { color-scheme: dark; }
body { background: #111113; color: #fafafa; font: 13px/1.5 ui-sans-serif, system-ui, sans-serif; margin: 0; padding: 28px 32px 80px; }
h1 { font-size: 18px; margin: 0 0 4px; }
p.lede { color: rgba(250,250,250,.6); margin: 0 0 24px; max-width: 66ch; }
h2 { border-top: 1px solid rgba(255,255,255,.12); font-size: 12px; letter-spacing: .08em; margin: 34px 0 14px; padding-top: 16px; text-transform: uppercase; }
.sheet { display: grid; gap: 10px; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); }
.cell { align-items: center; background: #09090b; border: 1px solid rgba(255,255,255,.12); border-radius: 10px; display: flex; flex-direction: column; gap: 6px; padding: 10px; }
.cell span { color: rgba(250,250,250,.38); font-family: ui-monospace, Menlo, monospace; font-size: 10.5px; }
.player { align-items: center; background: #09090b; border: 1px solid rgba(255,255,255,.12); border-radius: 12px; display: flex; flex-wrap: wrap; gap: 20px; padding: 16px 18px; position: sticky; top: 12px; z-index: 4; }
.stage { background: #09090b; border: 1px solid rgba(255,255,255,.12); border-radius: 12px; height: 260px; position: relative; width: 260px; }
.stage svg { inset: 0; position: absolute; }
label { align-items: center; color: rgba(250,250,250,.6); display: flex; font-size: 12px; gap: 7px; }
button { background: #18181b; border: 1px solid rgba(255,255,255,.12); border-radius: 999px; color: #fafafa; cursor: pointer; font: inherit; font-size: 12px; padding: 5px 13px; }
code { background: #18181b; border-radius: 4px; font-family: ui-monospace, Menlo, monospace; padding: 1px 5px; }
</style>
</head>
<body>
<h1>Mascot frames</h1>
<p class="lede">
  Every frame of the official export, drawn on one shared viewBox <code>${VB}</code> so nothing jumps.
  Play the tracks together and tell me which body range is the walk and how the eyes pair with it.
</p>

<div class="player">
  <div class="stage" id="stage"></div>
  <div>
    <label>body frame <input id="body" type="range" min="0" max="${(report.tracks[2]?.frames.length ?? 1) - 1}" value="0"><span id="bodyOut">0</span></label>
    <label>eye frame <input id="eye" type="range" min="0" max="${(report.tracks[3]?.frames.length ?? 1) - 1}" value="0"><span id="eyeOut">0</span></label>
    <label>fps <input id="fps" type="range" min="1" max="24" value="8"><span id="fpsOut">8</span></label>
    <label><input id="link" type="checkbox" checked> eyes follow body</label>
    <button id="play" type="button">play</button>
  </div>
</div>

${sheets}

<script>
const DATA = ${JSON.stringify({ viewBox: VB, tracks: report.tracks.map((t) => ({ fill: t.fill, frames: t.frames })) })};
const stage = document.getElementById("stage");
const body = document.getElementById("body");
const eye = document.getElementById("eye");
const fps = document.getElementById("fps");
const link = document.getElementById("link");
const play = document.getElementById("play");

function draw() {
  const b = DATA.tracks[2], e = DATA.tracks[3];
  const bi = Number(body.value) % b.frames.length;
  const ei = link.checked ? Math.floor(bi * e.frames.length / b.frames.length) : Number(eye.value);
  document.getElementById("bodyOut").textContent = bi;
  document.getElementById("eyeOut").textContent = ei;
  if (link.checked) eye.value = ei;
  stage.innerHTML =
    '<svg viewBox="' + DATA.viewBox + '" width="260" height="260"><path fill="' + b.fill + '" d="' + b.frames[bi] + '"></path>' +
    '<path fill="' + e.fill + '" d="' + e.frames[ei] + '"></path></svg>';
}

let timer;
play.addEventListener("click", () => {
  if (timer) { clearInterval(timer); timer = undefined; play.textContent = "play"; return; }
  play.textContent = "pause";
  timer = setInterval(() => {
    body.value = (Number(body.value) + 1) % DATA.tracks[2].frames.length;
    draw();
  }, 1000 / Number(fps.value));
});

for (const el of [body, eye, link]) el.addEventListener("input", draw);
fps.addEventListener("input", () => {
  document.getElementById("fpsOut").textContent = fps.value;
  if (timer) { clearInterval(timer); timer = setInterval(() => {
    body.value = (Number(body.value) + 1) % DATA.tracks[2].frames.length; draw();
  }, 1000 / Number(fps.value)); }
});

draw();
</script>
</body>
</html>
`;

writeFileSync(join(HERE, "mascot-frames.html"), html);
console.log(`shared viewBox: ${VB}`);
console.log(`wrote tools/mascot-frames.html (${report.tracks.reduce((n, t) => n + t.frames.length, 0)} frames)`);
